def exception(error):
    return {
    'status': 'error',
    'error': str(error)
}